### ISSUE TITLE
How to include mcf in Python?

### ISSUE THREAD

**Issue by filipetrocadoferreira** [nwojke/mcf#1]
I compiled everything but i'm not able to call pymcf

**Comment by nwojke** [comment]
If you have compiled with `-DMCF_BUILD_PYTHON=ON` you should see a `mcf.so` in `build/python_lib`. Do you have that?

If so, try the import from within `build/python_lib` or add the folder to your PYTHONPATH:

```
PYTHONPATH=[path_to_build/python_lib] ipython
```

If this doesn't work, what type of error do you get?

**Comment by filipetrocadoferreira** [comment]
I solve it. Because it was generating the Python lib using the wrong interpreter (3.5 instead of 2.7)

**Comment by nwojke** [comment]
Glad to hear that. Let me know if you run into any other issue or need some info on the poorly documented Python interface.
